---
title: "test_script"
author: "Hong Shi"
date: "3/19/2021"
output:
  bookdown::pdf_document2:
toc: FALSE

bibliography: references.bib
---
# Data Source

The data used for visualization is from `Ontario Data Catalogue`[@cite_catalogue]


# Citations
Citations used: `shiny` [@cite_shiny], `plotly`[@cite_plotly], `R`[@citeR], `tidyverse`[@cite_tidyverse], 
```{r, include=FALSE}
library(tidyverse)
library(here)
```
```{r}
test_university_data <- read_csv(here("uoft_enrollment_by_status.csv"))
```
```{r, include=FALSE}
test_university_data$enrollment_headcount
```

```{r, include= FALSE}
# Create tibble based on university enrollment data
university_data <- 
  tibble(
    enrollment_period = c("2012-2013","2012-2013","2012-2013","2012-2013","2013-2014","2013-2014","2013-2014","2013-2014","2014-2015", "2014-2015", "2014-2015","2014-2015","2015-2016","2015-2016","2015-2016","2015-2016","2016-2017","2016-2017","2016-2017","2016-2017", "2017-2018" ,"2017-2018", "2017-2018", "2017-2018", "2018-2019", "2018-2019", "2018-2019", "2018-2019")
,
type = c( "Undergraduate", "Undergraduate", "Graduate", "Graduate", "Undergraduate", "Undergraduate", "Graduate", "Graduate"    , "Undergraduate", "Undergraduate", "Graduate", "Graduate", "Undergraduate", "Undergraduate", "Graduate", "Graduate", "Undergraduate" ,"Undergraduate", "Graduate" ,     "Graduate" ,"Undergraduate", "Undergraduate", "Graduate", "Graduate"     
,"Undergraduate", "Undergraduate", "Graduate" ,"Graduate" ),
status = c("Domestic",  "International", "Domestic",  "International", "Domestic",  "International", "Domestic" ,     "International" ,"Domestic", "International", "Domestic", "International", "Domestic", "International", "Domestic", "International"
,"Domestic", "International", "Domestic", "International", "Domestic", "International", "Domestic", "International","Domestic" ,     "International", "Domestic", "International")
,
headcount = c(50671,  8564, 11817,  2163, 51234,  9477, 12283,  2407, 50900, 11025, 12659,  2598, 51424, 12296, 13041,  2777, 50850, 13486, 13618,  2988, 50000, 14947, 13960,  3097, 49401, 16319, 14339,  3495)
)

```
```{r, include=FALSE}
undergrad_data <- 
  university_data %>% 
  filter(type == "Undergraduate")
try_plot1 <- undergrad_data %>% 
  ggplot(aes(x = enrollment_period, y = headcount, fill = status))+
  geom_col(width = 0.7)+
  theme_minimal()+
  labs(title = "University of Toronto Enrollment Headcount by Enrollment Status 2012-2019",
       x = "Enrollment Period",
       y = "Headcount")+
  theme(text=element_text(size=12,  family="serif"),
                  plot.title = element_text(hjust = 0.5), legend.title = element_blank())+
  scale_fill_hue(c=70,  l=55)+
  scale_fill_manual(values = c("#619CFF","#FF3300"))
try_plot1
```

```{r, include=FALSE}

  undergrad_data %>% 
  ggplot(aes(x = enrollment_period, y = headcount, fill = status))+
  geom_col(width = 0.7)+
  theme_minimal()+
  labs(title = "University of Toronto Undergraduate Enrollment Headcount 2012-2019",
       x = "Enrollment Period",
       y = "Headcount")+
  theme(text=element_text(size=12,  family="serif"),
                  plot.title = element_text(hjust = 0.5), legend.title = element_blank()) 
  #ggsave(here("scripts/stackedbar_undergrad.png"))
```
```{r, include=FALSE}
grad_data <- 
  university_data %>% 
  filter(type == "Graduate")
try_plot11 <- grad_data %>% 
  ggplot(aes(x = enrollment_period, y = headcount, fill = status))+
  geom_col(width = 0.7)+
  theme_minimal()+
  labs(title = "University of Toronto Graduate Enrollment Headcount 2012-2019",
       x = "Enrollment Period",
       y = "Headcount")+
  theme(text=element_text(size=12,  family="serif"),
                  plot.title = element_text(hjust = 0.5), legend.title = element_blank())
try_plot11
#ggsave(here("scripts/stackedbar_grad.png"))
```


```{r, include=FALSE}
try_plot2 <- undergrad_data %>% 
  ggplot(aes(x = enrollment_period, y = headcount, group = status))+
  geom_line(aes(color = status))+
  geom_point(aes(color = status, shape = status), alpha = 0.8)+
  theme_minimal()+
  labs(title = "University of Toronto Undergraduate Enrollment Headcount 2012-2019",
       x = "Enrollment Period",
       y = "Headcount")+
  theme(text=element_text(size=12,  family="serif"),
                  plot.title = element_text(hjust = 0.5), legend.title = element_blank())+
  expand_limits(y = 0)
try_plot2
#ggsave(here("scripts/line_undergrad.png"))

```
```{r,include=FALSE}
try_plot22 <- grad_data %>% 
  ggplot(aes(x = enrollment_period, y = headcount, group = status))+
  geom_line(aes(color = status))+
  geom_point(aes(color = status), alpha = 0.8)+
  theme_minimal()+
  labs(title = "University of Toronto Graduate Enrollment Headcount 2012-2019",
       x = "Enrollment Period",
       y = "Headcount")+
  theme(text=element_text(size=12,  family="serif"),
                  plot.title = element_text(hjust = 0.5), legend.title = element_blank())+
  expand_limits(y = 0)
try_plot22
#ggsave(here("scripts/line_grad.png"))

```
\newpage

# References





